quarkus:
  info:
    enabled: true
    build:
      build-number: ${BUILD_NUMBER:999}
      jdk: ${java.version} (${java.vendor})
      os:
        name: ${os.name}
        version: ${os.version}
        architecture: ${os.arch}
    git:
      mode: full
